version: "3"

services:
  app-with-cache:
    build: .
    volumes:
      - ./laravel-app:/app
      - ./.composer/cache:/root/.composer/cache:cached
    working_dir: /app
    ports:
      - "8010:8010"
    command: php artisan serve --host=0.0.0.0 --port=8010

  app-without-cache:
    build: .
    volumes:
      - ./laravel-app:/app
    working_dir: /app
    ports:
      - "8020:8020"
    command: php artisan serve --host=0.0.0.0 --port=8020
